baseURL = "https://saasproductguy.com/"
languageCode = "en-us"
theme="ghostwriter"
title="SaaS Product Guy"
googleAnalytics = "UA-35051660-10"

[Author]
    name = "Jagan Ganti"

[Taxonomies]
    category = "categories"
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline ="SaaS Product Guy"
    description = ""
    twitter = "https://twitter.com/jagan123"
    linkedin = "https://linkedin.com/in/jagan123"
    email = "jagan.ganti@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedin = true
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimated reading time:"

[params.favicon]
    Enable = true

[Permalinks]
    post = "/:filename/"
    page = "/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
